"""rebuild_database_schema

Revision ID: 90a22a240412
Revises: 36727938e0bc
Create Date: 2026-07-01 13:50:23.197927
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '90a22a240412'
down_revision: str | None = '36727938e0bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.add_column('predictions', sa.Column('priority', sa.String(length=30), nullable=False))
    op.add_column('predictions', sa.Column('category_confidence', sa.Float(), nullable=False))
    op.add_column('predictions', sa.Column('priority_confidence', sa.Float(), nullable=False))
    op.add_column('predictions', sa.Column('sentiment_confidence', sa.Float(), nullable=False))
    op.add_column('predictions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('predictions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('predictions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'predictions', ['ticket_id'])
    op.drop_column('predictions', 'confidence')
    op.add_column('tickets', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('tickets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tickets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('tickets', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('tickets', 'deleted_at')
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'created_at')
    op.drop_column('tickets', 'source')
    op.add_column('predictions', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'predictions', type_='unique')
    op.drop_column('predictions', 'deleted_at')
    op.drop_column('predictions', 'updated_at')
    op.drop_column('predictions', 'created_at')
    op.drop_column('predictions', 'sentiment_confidence')
    op.drop_column('predictions', 'priority_confidence')
    op.drop_column('predictions', 'category_confidence')
    op.drop_column('predictions', 'priority')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'deleted_at')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
